import type { ColivingSpace } from '@/types';

export const mockColivingSpaces: ColivingSpace[] = [
  {
    id: '1',
    name: 'Nomad Haven Bali',
    address: 'Canggu, Bali, Indonesia',
    logoUrl: 'https://placehold.co/100x100.png',
    description: 'A vibrant community focused on surfing, yoga, and entrepreneurship. Features a large coworking space and regular events.',
    videoUrl: 'https://example.com/video-bali',
    slackLink: 'https://nomadhaven.slack.com',
    whatsappLink: 'https://chat.whatsapp.com/nomadbali',
    tags: ['surfing', 'yoga', 'coworking', 'community'],
    dataAiHint: 'beach community',
  },
  {
    id: '2',
    name: 'Lisbon Digital Lodge',
    address: 'Alfama, Lisbon, Portugal',
    logoUrl: 'https://placehold.co/100x100.png',
    description: 'Experience historic Lisbon while connecting with tech-savvy nomads. Close to cafes and cultural hotspots.',
    slackLink: 'https://lisbondigital.slack.com',
    tags: ['city life', 'tech', 'culture', 'networking'],
    dataAiHint: 'city tech',
  },
  {
    id: '3',
    name: 'Mountain CoLive Colorado',
    address: 'Denver, Colorado, USA',
    logoUrl: 'https://placehold.co/100x100.png',
    description: 'Perfect for outdoor enthusiasts. Offers easy access to hiking, skiing, and a supportive community of remote workers.',
    videoUrl: 'https://example.com/video-colorado',
    whatsappLink: 'https://chat.whatsapp.com/mountaincolive',
    tags: ['mountains', 'hiking', 'skiing', 'outdoors'],
    dataAiHint: 'mountain nature',
  },
  {
    id: '4',
    name: 'Tokyo Tech Nest',
    address: 'Shibuya, Tokyo, Japan',
    logoUrl: 'https://placehold.co/100x100.png',
    description: 'Immerse yourself in the heart of Tokyo. A modern coliving space for developers, designers, and creators.',
    slackLink: 'https://tokyotechnest.slack.com',
    tags: ['urban', 'tech', 'innovation', 'japan'],
    dataAiHint: 'city japan',
  },
  {
    id: '5',
    name: 'Cape Town Creatives',
    address: 'Sea Point, Cape Town, South Africa',
    logoUrl: 'https://placehold.co/100x100.png',
    description: 'Stunning ocean views and a hub for creative professionals. Enjoy braais, workshops, and collaborative projects.',
    videoUrl: 'https://example.com/video-capetown',
    tags: ['ocean', 'creative', 'design', 'art'],
    dataAiHint: 'ocean city',
  },
  {
    id: '6',
    name: 'Medellin Connect Hub',
    address: 'El Poblado, Medellín, Colombia',
    logoUrl: 'https://placehold.co/100x100.png',
    description: 'Known for its "eternal spring" climate and vibrant nomad scene. Offers Spanish lessons and salsa nights.',
    whatsappLink: 'https://chat.whatsapp.com/medellinconnect',
    tags: ['city vibe', 'culture', 'networking', 'spanish'],
    dataAiHint: 'city colombia',
  },
];
